### ISSUE TITLE
Original repo

### ISSUE THREAD

**Issue by TmLev** [kassane/awesome-concurrency#1]
Hello!

Please consider opening a PR with new articles to the original repo  https://gitlab.com/Lipovsky/awesome-concurrency instead of forking and keeping it here.

And it would be nice if you'd mention the author of this list in your fork, since they've done an outstanding job of collecting and structuring the articles and talks.

**Comment by kassane** [comment]
Hi @TmLev ,

Congratulations on the choice of materials. They are great and it is helping me in my testing and academic research.

Yeah, I will mention both the original repository and author. I only made one initial change. If you'd like to mention the reference I can accept PR in this fork.
Regarding adding to the original repository. I'll submit it to [gitlab](https://gitlab.com/Lipovsky/awesome-concurrency) also soon after this draft will have more relevant content.
